anamaria/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

anamariabrega/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('anamaria.urls')),
    path('receitas/', include('receitas.urls')),
    path('admin/', admin.site.urls),
]

receitas/urls.py
from django.urls import path

from . import views

app_name = 'receitas'
urlpatterns = [
    path('', views.ReceitaListView.as_view(), name='index'),
    path('create/', views.ReceitaCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ReceitaDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.ReceitaUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.ReceitaDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('category_list/', views.CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category'),
]

anamaria/models.py
from django.db import models

# Create your models here.

receitas/models.py
from django.db import models

# Create your models here.

from django.conf import settings
from datetime import datetime


class Post(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateTimeField(default=datetime.now, blank=True)
    content = models.CharField(max_length=255)
    image_url = models.URLField(max_length=255, null=True)

    def __str__(self):
        return f'{self.name} ({self.date})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField(default=datetime.now, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post, blank=True)

    def __str__(self):
        return f'"{self.name}"'

receitas/forms.py
from django import forms

from django.forms import ModelForm
from .models import Post, Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

anamaria/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    context = {}
    return render(request, 'anamaria/index.html', context)

def about(request):
    context = {}
    return render(request, 'anamaria/about.html', context)

receitas/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .temp_data import receita_data

from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from django.shortcuts import render, get_object_or_404

from django.views import generic

from .models import Post, Comment, Category
from .forms import CommentForm



class CategoryListView(generic.ListView):
    model = Category
    template_name = 'receitas/category_list.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'receitas/category.html'

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('receitas:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'receitas/comment.html', context)

class ReceitaListView(generic.ListView):
    model = Post
    template_name = 'receitas/index.html'

class ReceitaDetailView(generic.DetailView):
    model = Post
    template_name = 'receitas/detail.html'

class ReceitaCreateView(generic.CreateView):
    model = Post
    fields = [
            'name',
            'content',
            'image_url',
        ]
    template_name = 'receitas/create.html'
    success_url = '../'

class ReceitaUpdateView(generic.UpdateView):
    model = Post
    fields = [
            'name',
            'content',
            'image_url',
        ]
    template_name = 'receitas/update.html'
    success_url = '../../'

class ReceitaDeleteView(generic.DeleteView):
    model = Post
    template_name = 'receitas/delete.html'
    success_url = '../../'



# def list_receitas(request):
#     receita_list = Post.objects.all()
#     context = {'receita_list': receita_list}
#     return render(request, 'receitas/index.html', context)

# def detail_receita(request, receita_id):
#     receita = get_object_or_404(Post, pk=receita_id)
#     context = {'receita': receita}
#     return render(request, 'receitas/detail.html', context)

# def create_receita(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             receita_name = request.POST['name']
#             receita_content = request.POST['content']
#             receita_image_url = request.POST['image_url']
#             receita = Post(name=receita_name,
#                       content=receita_content,
#                       image_url=receita_image_url)
#             receita.save()
#             return HttpResponseRedirect(
#                  reverse('receitas:detail', args=(receita.id, )))
#     else:
#         form = PostForm()
#     context = {'form': form}
#     return render(request, 'receitas/create.html', context)

# def update_receita(request, receita_id):
#     receita = get_object_or_404(Post, pk=receita_id)

#     if request.method == "POST":
#         form = PostForm(request.POST)
#         if form.is_valid():
#             receita.name = request.POST['name']
#             receita.content = request.POST['content']
#             receita.image_url = request.POST['image_url']
#             receita.save()
#             return HttpResponseRedirect(
#                 reverse('receitas:detail', args=(receita.id, )))
#     else:
#         form = PostForm(
#             initial={
#                 'name': receita.name,
#                 'content': receita.content,
#                 'image_url': receita.image_url
#             })

#     context = {'receita': receita, 'form': form}
#     return render(request, 'receitas/update.html', context)

# def delete_receita(request, receita_id):
#     receita = get_object_or_404(Post, pk=receita_id)

#     if request.method == "POST":
#         receita.delete()
#         return HttpResponseRedirect(reverse('receitas:index'))

#     context = {'receita': receita}
#     return render(request, 'receitas/delete.html', context)

anamaria/templates/anamaria/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre Nós</h2>
<p>
Ana Maria Brega é um site especializado no oferecimento das receitas mais quentes do momento!
</p>

Oferecemos sempre os melhores tutoriais e todos eles são de deixar água na boca!
</p>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultrices condimentum finibus. Donec vel erat leo. Etiam et magna porttitor, vulputate nisi sed, rutrum massa. Nulla quis mattis nisl, ut facilisis justo. Phasellus mi nulla, varius ut ex sit amet, sodales bibendum est. Nullam suscipit urna in urna blandit, sit amet pellentesque arcu faucibus. Donec euismod pellentesque egestas. Pellentesque vel efficitur quam, at suscipit dolor. Quisque quis massa sapien. In hac habitasse platea dictumst. Vivamus imperdiet nisi vitae augue mattis rhoncus. Nullam nisl quam, sagittis nec faucibus sed, cursus nec mi.
</p>

<p>
Aenean iaculis vulputate tellus. Pellentesque et maximus lorem, eu vulputate libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus faucibus, tellus quis fermentum malesuada, tellus neque fermentum sem, ut vehicula libero nibh a mauris. Maecenas vel purus nec massa scelerisque tincidunt. Quisque sed mi sit amet tortor finibus fringilla. In imperdiet, turpis nec dictum aliquet, nunc neque cursus dui, vitae tempor lectus odio a sem. Ut dapibus at nisi ut condimentum. In hac habitasse platea dictumst. Nullam facilisis, velit in vehicula ornare, quam ex sollicitudin ex, ut cursus lectus odio at nisi. Pellentesque pulvinar semper arcu quis suscipit. Duis sed augue purus. Integer at augue id dui rhoncus consequat non id enim. Nam nisl est, placerat ut sollicitudin a, congue condimentum nibh. Sed sed quam erat.
</p>

{% endblock content %}

anamaria/templates/anamaria/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<br>
    <div class="ad-container">
        <div class="ad-box">
            <h2 class="ad-description">Faça as receitas mais quentes do momento</h2>
            <p class="ad-description">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis ipsa rem quasi illo ducimus quibusdam ullam id numquam aliquid quae?
            </p>
            <p class="ad-description">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit, fugiat?
            </p>
        </div>
        <div class="ad-image ad-cookie"></div>
    </div>
    <div class="text-block">
        {{ .Content }}
    </div>
{% endblock content %}

anamaria/templates/base.html
{% load static %} 

<!DOCTYPE html><html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Molle|Dancing Script|Roboto|Kaisei Tokumin|Lobster|Patrick Hand|Caveat|Myriad Pro">
    
</head>

<body>
    <header>
        <div class="logo-container">
            <img class="logo" src="{% static 'chef.png' %}" alt="logo" /> 
            <h1>Ana Maria Brega</h1>
        </div>
    </header>
    <nav>
        <ul class="menu">
            <li><a href="{% url 'index' %}">Página inicial</a></li>
            <li><a href="{% url 'receitas:category_list' %}">Categorias</a></li>
            <li><a href="{% url 'receitas:index' %}">Receitas</a></li>
            <li><a href="{% url 'about' %}">Sobre nós</a></li>
        </ul>
    </nav>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <h3>Copyright 2021: Ana Maria Brega</h3>
        <p>Lucas de Morais Souza</p>
    </footer>
</body>

</html>

receitas/templates/receitas/category.html
{% extends 'base.html' %}

{% block title %}
{{ category.name }}
{% endblock title %}

{% block content %}
<h2>{{ category.name }}</h2>
<p > {{ category.desc }} </p>

{% if category %}
<ul class="link-list">
    {% for post in category.posts.all %}
    <li>
        <a href="{% url 'receitas:detail' post.id %}">
            &#10139; {{ post.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Não foram encontradas receitas associadas à categoria {{ category.name }}.</p>
{% endif %}

{% endblock content %}

receitas/templates/receitas/category_list.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias</h2>

{% if category_list %}
<ul class="link-list">
    {% for category in category_list %}
    <li>
        <a href="{% url 'receitas:category' category.id %}">
            &#10139; {{ category.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Não foram encontradas categorias.</p>
{% endif %}

{% endblock content %}

receitas/templates/receitas/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Comentário para a Receita {{ post.name }}</h2>

<form action="{% url 'receitas:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'receitas:detail' post.id %}">Voltar para a página de receitas</a></p>
{% endblock content %}

receitas/templates/receitas/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Nova Receita</h2>
<form method="POST" action="{% url 'receitas:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

receitas/templates/receitas/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'receitas:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a receita "{{ post.name }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

receitas/templates/receitas/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }}
{% endblock title %}

{% block content %}
<h2>Receita de {{ post.name }}</h2>

<p>
    <h4><a href="{% url 'receitas:index' %}">&#8636; Retornar</a></h4>
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat, suscipit.
</p>
<h2>
    Categorias associadas
</h2>
<p class="ad-description"> 
{% for category in post.category_set.all %}        
    <a class="link-title" href="{% url 'receitas:category' category.id %}">{{ category.name }}</a> 
    <br>        
{% endfor %}
</p>

<div class="ad-container">
    <div class="ad-box">
        <h2 class="ad-description">{{ post.name }}</h2>
        <p class="ad-description">
            (Versão {{ post.date }})
        </p>

        <p class="ad-description">
            {{ post.content }}
        </p>
    </div>
    <div class="ad-image ad-cookie" style="background-image: url('{{ post.image_url }}');"></div>
</div>

<p>
    <h4><a href="{% url 'receitas:comment' post.pk %}">Inserir Comentário</a></h4>
</p>

<div class="ad-container">
    <div class="ad-box">
        {% if post.comment_set.all %}
            <h2 class="ad-description">Comentários</h2>
            {% for comment in post.comment_set.all reversed %}
            <p class="ad-description">
                {{ comment.text }}
                <br>
                <b><i>~ {{ comment.author }} ({{ comment.date }})</i></b>
            </p>
            {% endfor %}
            <br>
        {% else %}
            <h2 class="ad-description">Ainda não há comentários</h2>
            <br><br>
        {% endif %}
    </div>
</div>

<p>
    <h4><a href="{% url 'receitas:update' post.id %}">Atualizar Receita</a></h4>
</p>

<p>
    <h4><a href="{% url 'receitas:delete' post.id %}">Apagar Receita</a></h4>
</p>

{% endblock content %}

receitas/templates/receitas/index.html
{% extends 'base.html' %}

{% block title %}
Receitas
{% endblock title %}

{% block content %}
<h2>Todas as Receitas</h2>
<p class="link-label">Não encontrou a receita? <a class="link-title" href="{% url 'receitas:create' %}">Adicionar Nova Receita</a></p>
{% if post_list %}
<ul class="link-list">
    {% for post in post_list %}
    <li>
        <a href="{% url 'receitas:detail' post.id %}">
            &#10139; {{ post.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Não foi encontrada nenhuma receita</p>
{% endif %}

{% endblock content %}

receitas/templates/receitas/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados da Receita {{ post.name }}</h2>
<form method="POST" action="{% url 'receitas:update' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}